logo: /assets/flag_of_Earth.png
title: Dominique Marmen
description: Bonjour,
Je suis Dominique. Je suis inscrite au baccalauréat en génie logiciel et je prends présentement mon premier cours de code en python.
Je m'intéresse particulièrement aux monnaies digitales et aux nouvelles idées qu'elles font évoluer.
show_downloads: False
google_analytics:
theme: jekyll-theme-cayman
