theme: jekyll-theme-cayman
title: Dominique Marmen
description: "Citoyenne du monde, passionnée par l'économie et les sciences sociales, je m'intéresse à la manière dont nous organisons les sociétés.
Aujourd'hui, je souhaite participer à la transformation numérique et faire partie de ceux qui travailleront à construire les sociétés de demain.
Je m’intéresse particulièrement aux monnaies digitales et aux nouvelles idées qu’elles font évoluer."
